CREATE DATABASE DIO_LOJA;

USE DIO_LOJA;

CREATE TABLE PRODUTOS (
	CODIGO 			INT 		NOT NULL,
    DESCRICAO 		VARCHAR(50) NOT NULL,
    DATA_VALIDADE 	DATETIME,
    EAN				VARCHAR(15)	NOT NULL,
    IND_INATIVO 	INT 		NOT NULL DEFAULT 0
);

ALTER TABLE PRODUTOS
	ADD CONSTRAINT PK_PRODUTOS
		PRIMARY KEY (CODIGO);

CREATE INDEX IDX_PRODUTOS_EAN
		ON PRODUTOS(EAN);

INSERT INTO PRODUTOS VALUES (1, 'Nome do Produto', now(), '0AFKDVF517', 0);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, EAN) VALUES(2, 'Produto 2', 'ADAS151S1V');

CREATE TABLE LOJAS (
	CODIGO			INT 		NOT NULL,
    NOME 			VARCHAR(50) NOT NULL,
    IND_INATIVO 	INT 		NOT NULL DEFAULT 0,
    CONSTRAINT PK_LOJAS PRIMARY KEY (CODIGO)
);

INSERT INTO LOJAS (CODIGO, NOME) VALUES (1000, 'Manaus'), (2000, 'Recife'), (3000, 'Blumenau');

CREATE TABLE ESTOQUE (
	CODIGO_PRODUTO	INT 	NOT NULL,
    CODIGO_FILIAL	INT 	NOT NULL,
    QUANTIDADE		DECIMAL	NOT NULL DEFAULT 0,
    CONSTRAINT PK_ESTOQUE PRIMARY KEY (CODIGO_PRODUTO, CODIGO_FILIAL)
);

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES PRODUTOS (CODIGO);
        
ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_LOJAS
		FOREIGN KEY (CODIGO_FILIAL)
		REFERENCES LOJAS (CODIGO);

INSERT INTO ESTOQUE (CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (1, 1000, 5);
INSERT INTO ESTOQUE (CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (1, 2000, 10);


