USE DIO_LOJA;

SELECT * FROM PRODUTOS;

SELECT *
	FROM PRODUTOS
		WHERE DESCRICAO LIKE 'PRODUTO'; -- EXATAMENTE 'PRODUTO'
        
SELECT *
	FROM PRODUTOS
		WHERE DESCRICAO LIKE '%PRODUTO'; -- 'PRODUTO' NO FINAL
        
SELECT *
	FROM PRODUTOS
		WHERE DESCRICAO LIKE '%PRODUTO%'; -- 'PRODUTO' EM QUALQUER POSIÇÃO
        
SELECT COUNT(*)
	FROM PRODUTOS;
    

SELECT COUNT(*) AS TOTAL_PRODUTOS
	FROM PRODUTOS;
    
SELECT 	E.CODIGO_FILIAL,
		L.NOME,
        P.CODIGO,
        P.DESCRICAO,
        E.QUANTIDADE
	FROM ESTOQUE E INNER JOIN LOJAS L
		ON E.CODIGO_FILIAL = L.CODIGO
			INNER JOIN PRODUTOS P
				ON E.CODIGO_PRODUTO = P.CODIGO;
                
